project:
  type: book
  output-dir: docs

book:
  title: "Statistical Analysis"
  search: true
  reader-mode: true

  page-footer: 
    left: |
      Statistical Analysis was written by <a href="https://jacobtnyoung.github.io/">Jacob T.N. Young</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  site-url: https://jacobtnyoung.github.io/crj-303-textbook/
  repo-url: https://github.com/jacobtnyoung/crj-303-textbook
  repo-branch: main
  repo-actions: [issue]

  chapters:
    - index.qmd
    - 01-levels-of-measurement.qmd

format:
  html:
    theme: lux

    navbar:
      right:

      # add a link to report an issue
        - text: "Report an Issue"
          href: "https://github.com/jacobtnyoung/crj-303-textbook/issues"

    author-meta: "Jacob T.N. Young"

editor: visual